JakeChampion/polyfill-library

package.json, yarn.lock
It's required in the `updatebrowserstacklist` test
=> Add dotenv dev dependency

lib/index.js
When given an unsupported (possibly empty) UA string together with `unknown: 'ignore'` then `getPolyfills` returns only features that have the `always` flag set.
Example:
```
polyfillLibrary.getPolyfills({
features: {
Promise: {flags: ['always']},
JSON: {flags: []}
},
unknown: 'ignore'
}).then(console.log)
```
logs: `{ Promise: { flags: Set { 'always' } } }`
But `getPolyfillString` (called with the same options) returns no polyfills. The `always` flag is not respected.
With my little change, `getPolyfillString` returns the same polyfills as `getPolyfills`.
=> getPolyfillString without check for unsupported ua

README.md
I'm not sure if I'm allowed to contribute this, because <kbd>PRs welcome</kbd> linked me to [example.com](https://example.com)
=> Use contributing guide url for contributing guide links

tasks/node/updatesources.js
This is required to avoid the situation where the polyfill-library have too many file-descriptors open.
Fixes #128
=> Use Graceful-fs when updating/building third-party polyfills

polyfills/Map/polyfill.js
If an object with a null prototype is provided as a key to the `Map` polyfill then a `TypeError` is raised. I think this is expected:
```
$ node
> var key = Object.create(null);
undefined
> 1/key;
TypeError: Cannot convert object to primitive value
```
This code was changed [here](https://github.com/Financial-Times/polyfill-library/commit/65ca84c19359cee11ae5b549233ac85fafc70633#diff-aaebc3d5cda7f687fb935dad9a4a98ea) and I think this is where the bug was introduced as I've tried the previous code (`key === -0`) and it seems to work fine.
=> Fixes check for -0 in Map.set polyfill

package.json
Updating the repo and bug url's to point to the new repository since polyfill-library was moved out of polyfill-service.
=> chore: update repo and bug urls

lib/sources.js
Resolves https://github.com/Financial-Times/polyfill-library/issues/147
Resolves https://github.com/Financial-Times/polyfill-library/issues/148
=> Use caches for getPolyfillMeta, listAliases, and listPolyfills

polyfills/IntersectionObserver/config.json
fixes https://github.com/Financial-Times/polyfill-library/issues/173
=> Extend support of IntersectionObserver for Opera Mini

polyfills/Map/config.json, polyfills/Set/config.json
a `op_mob` code is used in a project to identify Opera Mini browser, i guess it's just a typo.
=> Rename opera_mob to op_mob in Set and Map polyfills config

polyfills/Set/config.json
Based on:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set
=> Edge browser support Set

polyfills/Object/is/config.json
Based on:
- http://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.is
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is
Edge mobile version is set when desktop version supports it
=> Update Object.is browser versions

package-lock.json, package.json, test/polyfills/test-individual-feature.js
Currently when a change is made to the package.json file it will cause all the tests within the project to be executed in CI, which is painfully painfully slow and labor-intensive. This is a real issue for the project because we have the ability to use an npm package as the source of a polyfill (known as third-party-polyfills) and this is used more and more by contributors to the project.
We can speed up the scenario where a third-party-polyfill has been added or updated within the project by making the CI test-runner aware of the changes made within the package.json file and figure out if the changes were for a third-party-polyfill or not.
=> Optimise CI testing for third-party-polyfills

.circleci/config.yml, .eslintignore, .gitignore, package-lock.json, package.json, polyfills/HTMLTemplateElement/config.json, polyfills/HTMLTemplateElement/detect.js, polyfills/HTMLTemplateElement/tests.js
With the growing popularity of UI libraries like `lit-html` and `hyperHTML` which use HTMLTemplateElement under-the-hood, I think it makes sense to include a minimal polyfill for that here.
One potential concern I have is that the polyfill author does not ship a minified version of the library in their npm module. I assume that means that we will have to either minify it ourselves or serve the polyfill un-minified.
=> add HTMLTemplateElement as an available polyfill

polyfills/Object/getOwnPropertyDescriptors/config.toml
It was added in the ECMA262 2017 edition -- https://www.ecma-international.org/ecma-262/8.0/#sec-object.getownpropertydescriptors
=> Add Object.getOwnPropertyDescriptors to the es2017 alias

polyfills/IntersectionObserver/config.toml
[`IntersectionObserver` is not available on Safari 12.0](https://caniuse.com/#feat=intersectionobserver), only from 12.1 onwards.
Fixes https://github.com/Financial-Times/polyfill-library/issues/285
=> Polyfill IntersectionObserver on Safari < 12.1

polyfills/AbortController/config.toml
Fixes #334 .
Samsung Internet does not support AbortController at all [source from MDN](https://developer.mozilla.org/en-US/docs/Web/API/AbortController).
=> Load AbortController for all version of Samsung browser

polyfills/Event/focusin/detect.js
in order to prevent focusin from accidentally scrolling chrome, setting it a `position:fixed` does the trick. Yet, as this is not widely used and impacts fewer browsers, I would rather like to removing this from default polyfill and give to the developer the liberty of having this detection run. Modifying the dom is always costly!
=> prevent focusin detection from scrolling

.circleci/config.yml, tasks/node/build-circleci-config.js
remove requires which are redundant since the test_0 already has them and all the other test tasks require test_0
=> simplify circle config

polyfills/Array/prototype/copyWithin/config.toml
browser support taken from MDN -- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/copyWithin#Browser_compatibility
=> do not serve copywithin polyfill to edge 12 or above

.circleci/config.yml
separate the different browsers into separate jobs so we can avoid rerunning the tests on every browser if only a subset has failed such as ie
=> speed up circleci retries

polyfills/Object/keys/config.toml
`Object.keys` must be polyfilled for IE11 because although that function exists, it uses the ES5 behavior where only object arguments are allowed.
Closes #294
=> Polyfill Object.keys for IE11

polyfills/Array/prototype/flat/config.toml, polyfills/Array/prototype/flatMap/config.toml, polyfills/Object/fromEntries/config.toml, polyfills/String/prototype/trimEnd/config.toml, polyfills/String/prototype/trimStart/config.toml
ECMAScript 2019 introduced a few new built-in functions: flat and flatMap on Array.prototype for flattening arrays, Object.fromEntries for directly turning the return value of Object.entries into a new Object, and trimStart and trimEnd on String.prototype as better-named alternatives to the widely implemented but non-standard String.prototype.trimLeft and trimRight built-ins.
fixes https://github.com/Financial-Times/polyfill-library/issues/329
=> Add es2019 alias for all the new features which were added to the spec in that version

polyfills/Element/prototype/nextElementSibling/config.toml, polyfills/Element/prototype/nextElementSibling/detect.js, polyfills/Element/prototype/nextElementSibling/polyfill.js, polyfills/Element/prototype/nextElementSibling/tests.js, polyfills/Element/prototype/previousElementSibling/config.toml, polyfills/Element/prototype/previousElementSibling/detect.js, polyfills/Element/prototype/previousElementSibling/polyfill.js, polyfills/Element/prototype/previousElementSibling/tests.js
Raising this to see if I'm on the right track.
So it looks like this feature is used in the node type of `NonDocumentTypeChildNode` since it can be `Element` and `CharacterData`. Does this block this improvement, or can we continue and consider a wider `NonDocumentTypeChildNode` polyfill later that would also sort CharacterData?
- [NonDocumentTypeChildNode.nextElementSibling
](https://developer.mozilla.org/en-US/docs/Web/API/NonDocumentTypeChildNode/nextElementSibling#Polyfill_for_Internet_Explorer_9_and_Safari)
Closes https://github.com/Financial-Times/polyfill-library/issues/338
=> Add nextElementSibling and previousElementSibling polyfills

polyfills/Intl/update.task.js
fix bug introduced here : https://github.com/Financial-Times/polyfill-library/commit/00fd3a6a2d8befde00bc28d7a0f2837e0bfb642d#diff-ac17574cf1e592188b7d0744e9071fc5R94
>Intl.js:7 Uncaught RangeError: Incorrect locale information provided
at Function.supportedLocalesOf (<anonymous>)
at Intl.js:7
at Object.<anonymous> (Intl.js:2160)
at Object.<anonymous> (Intl.js:2160)
at __webpack_require__ (bootstrap:19)
at Module.<anonymous> (get-iterator.js:9)
at __webpack_require__ (bootstrap:19)
at bootstrap:83
at bootstrap:83
```js
Intl.NumberFormat.supportedLocalesOf && 
Intl.Collator.supportedLocalesOf('af-NA.js').length === 1 && 
Intl.DateTimeFormat.supportedLocalesOf('af-NA.js').length === 1 && 
```
=> intl : fix update task

polyfills/Element/prototype/nextElementSibling/config.toml, polyfills/Element/prototype/previousElementSibling/config.toml
I missed these in https://github.com/Financial-Times/polyfill-library/pull/484
=> Add spec links to [next|previous]ElementSibling

polyfills/AudioContext/detect.js
ensure the audio polyfill only runs in browsers which have webkitAudioContext because it depends on this to exist
=> Fix AudioContext feature detection

polyfills/Intl/PluralRules/update.task.js, polyfills/Intl/update.task.js
We were seeing this error :
```
Error: No locale data has been added to IntlPluralRules for: , or the default locale: en
```
We think we traced it to the detect script that was updated a few days ago.
=> intl update script : fix detect

polyfills/Event/focusin/detect.js
This situation occurs when the feature-detect is loaded in the <head> element of the document.
Fixes https://github.com/Financial-Times/polyfill-library/issues/511
=> Make the focusin detect work when document.body does not yet exist

.circleci/config.yml, .gitignore, test/polyfills/compat.js, test/polyfills/remotetest.js, test/polyfills/test-job.js, test/polyfills/update-polyfill-targeting.js
This creates a CircleCI job to run once a day which:
- Runs the tests without any polyfills
- Runs the tests with polyfills
- Updates each polyfill config file which need to be updated (I.E. Chrome latest no longer needs polyfills for `Map.from` or something like that)
- Creates a pull-request for each separate polyfill update
=> Check and update polyfill targeting once a day automatically

polyfills/Math/hypot/config.toml
as it's implementation does not return `NaN` for `Math.hypot(undefined,0)` and instead returns `0`
=> Ship Math.hypot to chrome 77

polyfills/AbortController/config.toml
The `config.toml` seems to have old info from the original pull request where another polyfill was considered.
This change updates the config to reflect the current polyfill.
=> abortcontroller : update config.toml

polyfills/Element/prototype/matches/config.toml
fixes https://github.com/Financial-Times/polyfill-library/issues/541
Browser support gathered from MDN -- https://developer.mozilla.org/en-US/docs/Web/API/Element/matches#Browser_compatibility
=> serve element.prototype.matches to edge versions below 18

polyfills/Map/polyfill.js
Currently the `replace` function does nothing because it is invoked on the empty string.
This PR adds parentheses around the string for which the `replace` function was intended.
=> Map polyfill bug-fix: Remove dot from metakey

lib/index.js, lib/sources.js
This fixes an error I was getting when a polyfill was requested that doesn't exist.
=> catch exception when polyfill file doesn't exist

polyfills/Intl/PluralRules/config.toml
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules#Browser_compatibility) and some exceptions we're seeing, Edge <18 doesn't ship with support for Intl.PluralRules
Addresses #633
=> Polyfill Intl.PluralRules on Edge <18

package-lock.json, package.json, polyfills/smoothscroll/config.toml, polyfills/smoothscroll/detect.js, polyfills/smoothscroll/patch.jsdiff, tasks/node/updatesources.js, test/polyfills/compat.js, test/polyfills/test-job.js
Previously, polyfill-library used smoothscroll-polyfill. That library is no longer well-maintained and is missing some parts of the smoothscroll spec.
This commit swaps in seamless-scroll-polyfill, which is a better-maintained fork of smoothscroll-polyfill.
Resolves #657
=> Use seamless-scroll-polyfill for smoothscroll

polyfills/Map/polyfill.js, polyfills/Map/tests.js
This fix resolves an issue where classes are used as Map keys.
The present behavior is that a base class and sub class resolves the same entry. The desired behavior is for them to resolve to different entries.
Test that reproduces the bug and the fix are included.
This regression has made it impossible to use Polyfill.io for aurelia apps in IE.
=> Fix Map regression introduced in #219

polyfills/Promise/prototype/finally/config.toml
I was able to track down, through a bunch of investigation, that `Promise.prototype.finally` wasn't actually added into Chrome until at least version 63.0.3219
I'm hoping that the main lib supports specifying minor versions this way, otherwise we might have to just change this to `< 64`?
=> Fix "finally" support for Chrome 63

lib/index.js
The suggestion came from @jossnaz in the polyfill-service repo https://github.com/Financial-Times/polyfill-service/issues/2280#issuecomment-665852215
=> Improve the message when no polyfills are required to be served to the requesting browser

.github/workflows/test-polyfills.yml
This should ensure we don't get lots of failing pull-request checks due to browserstack cancelling the test-run due to having too many tests in there queue.
=> ensure only one pull-request runs the browserstack tests at a single time

.github/workflows/test-polyfills.yml
This is because the workflow will fail due to not having access to the secrets required for browserstack to run.
We want to exit early because then we will not have this workflow run be marked as a failure. Having the workflow get marked as a failure will make a GitHub notifcation/email be sent to whoever follows the builds for polyfill-library (such as myself).
=> exit test-polyfills workflow early if running from a forked repo.

test/polyfills/server.js
Noticed that a lot of work is done in `test/polyfills/server.js:132` `testablePolyfills` and that this work is the same for each tested polyfill.
By memoizing the results tests run a lot faster.
Before :
After :
--------------
When combined with a [parallel build script](https://github.com/Financial-Times/polyfill-library/issues/887)
Chrome before :
Chrome after :
=> memoize testablePolyfills in test/polyfills/server.js

package-lock.json, package.json, polyfills/.eslintrc, polyfills/Array/prototype/sort/detect.js, polyfills/DOMTokenList/prototype/@@iterator/detect.js, polyfills/DOMTokenList/prototype/replace/detect.js, polyfills/DocumentFragment/config.toml, polyfills/DocumentFragment/detect.js, polyfills/DocumentFragment/polyfill.js, polyfills/DocumentFragment/prototype/append/polyfill.js, polyfills/DocumentFragment/prototype/prepend/polyfill.js, polyfills/DocumentFragment/tests.js, polyfills/Object/seal/detect.js, polyfills/Reflect/apply/detect.js, polyfills/Reflect/construct/detect.js, polyfills/Reflect/defineProperty/detect.js, polyfills/Reflect/deleteProperty/detect.js, polyfills/Reflect/get/detect.js, polyfills/Reflect/getOwnPropertyDescriptor/detect.js, polyfills/Reflect/getPrototypeOf/detect.js, polyfills/Reflect/has/detect.js, polyfills/Reflect/isExtensible/detect.js, polyfills/Reflect/ownKeys/detect.js, polyfills/Reflect/preventExtensions/detect.js, polyfills/Reflect/set/detect.js, polyfills/Reflect/setPrototypeOf/detect.js, test/polyfills/server.js
resolves : https://github.com/Financial-Times/polyfill-library/issues/520
- add a [linter rule plugin](https://github.com/romainmenke/eslint-plugin-uncalled-iife) to detect uncalled `IIFE` in `detect.js`
- ~~verify that calling `detect.js` as a function throws~~
- fix some `detect.js` files
- fix `DocumentFragment` polyfill
----------
I would have preferred to include a custom eslint rule in the `polyfill-library` repo but `eslint` does not support this.
The only way was to create a separate package containing the rule and publish it on npm.
This package is really small and I do not mind maintaining it when eslint introduces breaking changes.
There are cases that can't be caught this way. (named functions that aren't called)
Testing for uncalled `IIFE`'s exposed some issues with the …
=> more tests and lints for feature detect.js

.github/workflows/test-polyfills.yml, .github/workflows/unit-test.yml, polyfills/ResizeObserver/tests.js, test/polyfills/test-director.handlebars
Noticed that `ResizeObserver` tests sometimes fail. Did not find one root cause but is most likely caused by `requestAnimationFrame` not firing reliably (load on Browserstack vm?).
Extending timeouts and adding a few retries should reduce the number of failures.
--------------
Also added a per commit cache of the `polyfills/__dist` folder.
This is used only to share the build result between steps in a single run.
Full test suite now takes ±20 minutes (down from ±25 minutes)
=> attempt at less flaky ResizeObserver tests

polyfills/AbortController/tests.js, test/polyfills/server.js, test/polyfills/test-director.handlebars
Handlebars was used before to turn the feature list into a comma separated string which resulted in a trailing comma.
`Array.join` is now used which does not have a trailing comma.
--------
ci fails in chrome on `AbortController`. This was never tested before as it is the first feature. (order is inversed twice I think)
--------
ci running now and seems to work better. Replace fetch calls to `https://httpstat.us/200?sleep=1000` with an internal "sleep" endpoint.
We had an issue some time ago where older OS's on Browserstack couldn't connect over `https` anymore because of the Sectigo cert expiry. My best guess is that this was the same issue.
Will run CI again to make sure it isn't just flacky and accidentally passing now.
--------
all green on this end
=> fix : test director skips single feature

package.json, polyfills/Intl/DateTimeFormat/config.toml, polyfills/Intl/DisplayNames/config.toml, polyfills/Intl/NumberFormat/config.toml, polyfills/Intl/PluralRules/config.toml, polyfills/Intl/RelativeTimeFormat/config.toml, polyfills/Intl/getCanonicalLocales/config.toml, tasks/clean.js
While testing `Intl` and switching between versions I had some errors because the update tasks add nested polyfills under `~locale`.
Example scenario :
- there is no change between versions in `polyfills/Intl/NumberFormat/polyfill.js`
- `polyfills/Intl/NumberFormat/~locale/af-NA/polyfill.js` does have a change between versions
- `tasks/updatesources.js` sees no change in `polyfills/Intl/NumberFormat/polyfill.js` and stops early
- `polyfills/Intl/NumberFormat/~locale/af-NA/polyfill.js` is never updated.
This change adds a `clean` entry to `config.toml` with a list of paths to remove per polyfill.
------------
note :
This is only an issue locally, not in CI as the files in question are ignored by git.
They never exist in CI but can exist locally.
=> add Polyfill specific cleanup tasks

test/polyfills/server.js
Result when deleting `detect.js` for a polyfill : 
This should make it easier to spot this kind of issue : https://github.com/Financial-Times/polyfill-library/pull/913#issuecomment-734773203
There the test has a syntax error in older browsers when `detect.js` is missing (`return ();`).
[CI Results](https://github.com/romainmenke/polyfill-library/runs/1470577858)
=> fail tests on missing detect source with better feedback

polyfills/DOMTokenList/prototype/replace/polyfill.js, polyfills/_ESAbstract/GetSubstitution/polyfill.js
When the `DOMTokenList.prototype.replace` was followed in the bundle by another IIFE polyfill it would throw this error :
`Uncaught TypeError: (intermediate value)(...) is not a function`
[spec](https://www.ecma-international.org/ecma-262/5.1/#sec-7.9)
```js
// DOMTokenList.prototype.replace
(function () {
console.log('hello');
})()
// Other polyfill with IIFE pattern
(function() {
console.log('world!');
}());
// 🔥 
```
------------
Found the same issue in `_ESAbstract/GetSubstitution`
=> fix unterminated polyfills.

polyfills/WeakMap/config.toml, polyfills/WeakMap/polyfill.js
_another small one_
`WeakMap` has a check for `'toStringTag' in Symbol` in a test but no dependency on it.
Added the dependency and defined `WeakMap.prototype[Symbol.toStringTag]` in the polyfill.
=> WeakMap fixes

polyfills/Object/create/tests.js, polyfills/Object/defineProperty/tests.js, polyfills/Object/entries/tests.js, polyfills/Object/getPrototypeOf/polyfill.js, polyfills/Object/keys/polyfill.js, polyfills/Object/keys/tests.js, polyfills/Symbol/polyfill.js
Update : test skipped in IE8 with a check for getters support.
--------
Notes :
(1) Symbol polyfill wraps some Object methods but didn't set a correct name for the wrapper function.
(2) `Object.create` sets `__proto__` via assignement. This makes `__proto__` enumerable.
Unsure if this should be fixed in `Object.create` or `Object.keys`. (now patched in `Object.keys`).
(3) `Object.defineProperty` has a feature test for `Object.create` but actually needed a check for getters support.
Fixed the test and added more which do not require getters.
(4) Some tests had a lot of `proclaim...` statements, making it harder to determine why something failed.
Splitting these up helped.
(5) **still broken**
Somehow it is not possible to get the prototype of the result of `Object.create(new fn)`.
The same …
=> Object fixes

polyfills/Blob/polyfill.js, polyfills/Blob/tests.js, polyfills/URL/polyfill.js, polyfills/fetch/tests.js
The Blob polyfill also wrapped the URL polyfill.
Added tests for any functionality that was touched and modified the polyfill.
Also added a minimal test for `fetch`.
This makes it available in combination tests.
=> fix URL polyfill by no longer overwriting it in the Blob polyfill

test/polyfills/remotetest.js, test/polyfills/server.js, test/polyfills/test-director.handlebars, test/polyfills/test-job.js, test/polyfills/test-runner.handlebars
The current way of testing where only the needed polyfills are loaded must remain.
This tests if dependencies are correctly configured. Loading all polyfills for a browser would make it impossible to verify dependencies in a polyfill config.
IE8 also runs out of memory when loading all polyfills needed for IE8 on each test.
---------------
This change adds a new range of test jobs :
- Each browser now has at least 2 jobs.
One with and one without all polyfills in combination.
- IE8 and IE9 shard their tests.
result :
- we keep the original way of testing
- IE8 no longer runs out of memory when loading all polyfills
- IE9 was starting to struggle towards the end, splitting them up as a precaution.
This change does make CI slower again 🙁 
But running more tests just takes more time.
Run …
=> isolate test runs with and without polyfill combinations

polyfills/Reflect/defineProperty/tests.js, polyfills/Reflect/deleteProperty/tests.js, polyfills/Reflect/get/tests.js, polyfills/Reflect/isExtensible/tests.js, polyfills/Reflect/preventExtensions/tests.js, polyfills/Symbol/polyfill.js
_smaller change_
Reflect has a couple of tests for `freeze` and variants.
These now have better checks to detect polyfills for older browsers which don't really freeze anything.
There was one failure in `Reflect.get` caused by a missing check in `Symbol`
```diff
- this[internalSymbol]['@@' + uid]
+ this[internalSymbol] && this[internalSymbol]['@@' + uid]
```
=> Reflect fixes

polyfills/String/fromCodePoint/config.toml
I think there should be `"es2015"` in the `aliases` of `String.fromCodePoint`, what do you think?
Please confirm.
=> add "es2015" to the aliases of String.fromCodePoint

tasks/buildsources/buildsources-child-proc.js
see : https://github.com/Financial-Times/polyfill-library/pull/945#issuecomment-746533357
- `Error handling ...` was confusing. 
- `Error` instances where logged as `{}`
```
{
name: 'Build error',
message: 'Error while building: _TypedArray',
error: {
message: 'Internal polyfill called _TypedArray is not targeting all supported browsers correctly. It should be: \n' +
'android = "*"\n' +
'bb = "*"\n' +
'chrome = "*"\n' +
'edge = "*"\n' +
'edge_mob = "*"\n' +
'firefox = "*"\n' +
'firefox_mob = "*"\n' +
'ie = "*"\n' +
'ie_mob = "*"\n' +
'ios_chr = "*"\n' +
'ios_saf = "*"\n' +
'op_mini = "*"\n' +
'op_mob = "*"\n' +
'opera = "*"\n' +
'safari = "*"\n' +
'samsung_mob = "*"\n',
error: {}
}
}
```
=> make sure errors contain useful messages

.eslintignore, .gitignore, polyfills/ArrayBuffer/config.toml, polyfills/HTMLCanvasElement/prototype/toBlob/config.toml, polyfills/Math/fround/config.toml, test/node/lib/test-index.js
The numbers were taken from MDN -- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#Browser_compatibility
Fixes https://github.com/Financial-Times/polyfill-library/issues/667
=> Update targeting for TypedArray polyfills

.github/workflows/test-polyfills.yml
I thought the timeout would apply to each run in the matrix, but it is a "global" timeout.
https://github.com/Financial-Times/polyfill-library/actions/runs/434646466
=> fix test polyfill timeout

polyfills/smoothscroll/detect.js
I noticed the `smoothscroll` polyfill wasn't patching properly in Safari when using the polyfill-service. The first part of the detect logic returns `false` (indicating the need for the polyfill), while the second returns `true`. However, when wrapping the detect logic with `!()` for the `?flags=gated` case, it evaluates to `false` due to the `||` operator. 
This PR updates the logic from `||` to `&&`.
Please let me know if there is any more info I can provide or things I forgot to address with this PR.
=> Update smoothscroll detect logic

polyfills/WebAnimations/config.toml
~Sourced from the spec : https://www.w3.org/TR/web-animations-1/#programming-interface~
~Verified in the source that these features are polyfilled : https://github.com/web-animations/web-animations-js~
Only added `Element.prototype.animate` based on [this table](https://github.com/web-animations/web-animations-js/blob/dev/docs/experimental.md)
=> Add alias for web animations polyfill

.github/workflows/auto-approve.yml, .github/workflows/sync-repo-labels.yml, package-lock.json
We have workflows that currently fail to run correctly for pull-requests from forks or pull-requests from dependabot. The reason is because those workflows are being triggered by the 'pull_request' event, which does will use a restricted github api token for pull-requests from forks or dependabot for security reasons.
For our workflows which are 'safe' (meaning they do not checkout the code or execute the code in the repository), we can change their trigger from 'pull_request' to 'pull_request_target', which uses a github api token with more permissions, specifically it has permission to read/use secrets, which are the things are workflows require.
Our workflows are safe, they do not checkout or execute the code from the repository, so we should change to using `pull_request_target` to …
=> use pull_request_target and not pull_request for the safe workflows

polyfills/Intl/DisplayNames/config.toml, polyfills/Intl/ListFormat/config.toml, polyfills/Intl/Locale/config.toml, polyfills/Intl/NumberFormat/config.toml, polyfills/Intl/PluralRules/config.toml, polyfills/Intl/RelativeTimeFormat/config.toml, polyfills/Intl/getCanonicalLocales/config.toml
I've faced that 7 meta config docs links on https://developer.mozilla.org/ point to Deutch `/de/` language version, moreover, 4 of them result in 404. This fix replaces these wrong links with correct `/en-US/` ones
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Intl/getCanonicalLocales
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/listformat
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/PluralRules
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames …
=> Doc links fix

polyfills/URL/config.toml, polyfills/URL/detect.js, polyfills/URL/polyfill.js, polyfills/URL/tests.js
fixes : #1048
-----------
As far as I can tell there where 2 issues.
- the detect script was too broad and didn't target new features (e.g. `URLSearchParams.prototype.sort`)
- `Array.from` was used but with it's own fallback and without declaring it as a dependency. Seems to work better with the `Array.from` polyfill.
Some WPT tests included here failed, but nothing truly major imho.
----------
_CI doesn't run on Firefox 37_
test url : http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=URL
browserstack url : https://live.browserstack.com/dashboard#os=OS+X&os_version=El+Capitan&browser=Firefox&browser_version=37.0&zoom_to_fit=true&full_screen=true&resolution=responsive-mode&speed=1
Test `URLSearchParams iterable methods` covers the issue.
This test was previously …
=> URLSearchParams : [err] keys is not a function

polyfills/Array/from/config.toml, polyfills/Array/from/detect.js, polyfills/Map/config.toml, polyfills/Set/config.toml, polyfills/Symbol/iterator/tests.js, polyfills/URL/config.toml, polyfills/URL/tests.js
Two issues found :
- `Array.from` is supported natively in some browsers without the ability to process iterables
- `Set` and `Map` polyfills were not loaded in browsers that needed `Set|Map.prototype[Symbol.iterable]`
Full test run (including polyfill combinations) : https://github.com/romainmenke/polyfill-library/actions/runs/838607240
fixes : #1053
=> ensure Map and Set iterators are polyfilled

test/polyfills/remotetest.js
```diff
Failures:
- ie/8.0:
-> document.elementsFromPoint document.elementsFromPoint returns all the elements at the specified coordinates
-      http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=document.elementsFromPoint&feature=document.elementsFromPoint
+      http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=document.elementsFromPoint
p deepStrictEqual p,div,body,html
```
Tested on node 8 -> 16
------
duplicate `feature` param bug was introduced in https://github.com/Financial-Times/polyfill-library/pull/997
=> better url logs for failing ci tests

test/polyfills/server.js
see : https://github.com/Financial-Times/polyfill-library/runs/2815491287?check_suite_focus=true
In this test we load all polyfills.
This means both "all" and "golden" are loaded and polyfilled, but they overlap.
Currently there is no mechanism to ensure that two polyfills are not loaded together.
I think that in itself is fine, including both is essentially a user error.
I added a filter in `server.js` to skip "golden" polyfill.
Tests for "golden" must work with the data from "all"
=> fix polyfill combination with time zone data

polyfills/URL/config.toml, polyfills/URL/polyfill.js, polyfills/URL/tests.js, polyfills/fetch/config.toml, polyfills/fetch/tests.js
should fix : https://github.com/Financial-Times/polyfill-library/issues/870
There is also a minification issue with an `iife` in the URL polyfill.
I added a few more semicolons around the `iife`'s here.
I can only reproduce it against polyfill.io so I am not sure it is fully fixed.
=> fix `URL` + `fetch` interop

polyfills/Intl/DateTimeFormat/config.toml, polyfills/Intl/DateTimeFormat/~timeZone/all/config.toml, polyfills/Intl/DateTimeFormat/~timeZone/golden/config.toml
fixes : #1075
Exact copy of `Intl.DateTimeFormat` browser config.
=> add timeZone data in all browsers that need Intl.DateTimeFormat

polyfills/fetch/config.toml, polyfills/fetch/detect.js, polyfills/fetch/tests.js
The `fetch` polyfill `detect.js` only checked against basic support.
This change will make more feature available even when using the `gated` flag.
=> check for AbortSignal feature in fetch detect.js

polyfills/Intl/DateTimeFormat/config.toml, polyfills/Intl/DateTimeFormat/detect.js, polyfills/Intl/DateTimeFormat/update.task.js
see : https://github.com/Financial-Times/polyfill-library/commit/af38c6a9a9fda2b45b4410117399f3ad4fabe4d9
tests : https://mrhenry.github.io/web-tests/#1bc7e152-dce1-46cb-a6df-08e5f181d84d
(tests assume that `polyfill.io` has the latest version of `polyfill-library`, so there are false negatives there at the moment)
This should also resolve issues with the polyfill not being applied with the gated flag.
=> update Intl.DateTimeFormat config and detect

polyfills/MediaQueryList/prototype/addEventListener/tests.js
see : https://github.com/Financial-Times/polyfill-library/actions/workflows/test-polyfills-weekly.yml
=> add retries to MediaQueryList tests as these have proven flaky

polyfills/DOMTokenList/prototype/@@iterator/config.toml
Apparently `9-12` is an invalid semver range.
`semver.satisfies`  just returns `false` in case of errors, so this went undetected.
https://github.com/Financial-Times/polyfill-useragent-normaliser/blob/master/compilers/node.js#L128
https://github.com/npm/node-semver/blob/main/functions/satisfies.js#L6
=> Update config.toml for DOMTokenList.prototype.@@iterator

.github/workflows/test-polyfills.yml
Currently running CI from a fork is no longer possible on the forked repo.
Allowing `workflow_dispatch` makes it possible to run CI on the fork.
It does require bringing your own credentials for browserstack.
But for regular contributors it is very handy to run all tests before opening a pull request.
=> allow workflow_dispatch in test-polyfills.yml

polyfills/DOMTokenList/prototype/@@iterator/config.toml
see : https://github.com/Financial-Times/polyfill-library/runs/4178779412?check_suite_focus=true
```
- ie/9.0:
-> DOMTokenList.prototype.@@iterator finally returns a done object
http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=DOMTokenList.prototype.@@iterator
Unable to get value of the property '__symbol:iterator0.336679911648032571': object is null or undefined
```
It seems this one was broken but never tested because : https://github.com/Financial-Times/polyfill-library/commit/66bf782835b1983933cffd3ebb454ca5859921a4
(config for `forEach` : https://github.com/Financial-Times/polyfill-library/blob/109533b9f9965483c4be848fb48943854d0e4526/polyfills/DOMTokenList/prototype/forEach/config.toml)
=> fix DOMTokenList.prototype.@@iterator

.github/contributing.md, .github/workflows/test-from-fork.yml
- manually triggered runs only
- simplified as much as possible (doesn't cancel runs when pushing a new commit quickly)
- add a guide on how to set this up
=> add test workflow for forks and document how to use these

polyfills/Array/prototype/at/config.toml, polyfills/Array/prototype/at/detect.js, polyfills/Array/prototype/at/polyfill.js, polyfills/Array/prototype/at/tests.js, polyfills/String/prototype/at/config.toml, polyfills/String/prototype/at/detect.js, polyfills/String/prototype/at/polyfill.js, polyfills/String/prototype/at/tests.js, polyfills/TypedArray/prototype/at/config.toml, polyfills/TypedArray/prototype/at/detect.js, polyfills/TypedArray/prototype/at/polyfill.js, polyfills/TypedArray/prototype/at/tests.js, polyfills/_ESAbstract/LengthOfArrayLike/config.toml, polyfills/_ESAbstract/LengthOfArrayLike/polyfill.js, polyfills/_ESAbstract/ToIntegerOrInfinity/config.toml, polyfills/_ESAbstract/ToIntegerOrInfinity/polyfill.js
`Array.prototype.at`, `String.prototype.at`, and `TypedArray.prototype.at` were added as part of ES2022 and have been supported by Chrome, Firefox, and Opera since July/August 2021.
=> Adds `Array.prototype.at`, `String.prototype.at`, and `TypedArray.prototype.at` polyfills

polyfills/AggregateError/tests.js, polyfills/Promise/allSettled/tests.js, polyfills/Promise/any/tests.js
This PR improves tests for `Promise.any`, `Promise.allSettled`, and `AggregateError` polyfills so that they run in all browsers.
=> Improves iterator tests for `Promise.any`, `Promise.allSettled`, and `AggregateError` polyfills

polyfills/ArrayBuffer/config.toml, polyfills/ArrayBuffer/patch.jsdiff, polyfills/ArrayBuffer/update.task.js, polyfills/TextEncoder/config.toml, polyfills/TextEncoder/polyfill.js, polyfills/TypedArray/prototype/at/config.toml, polyfills/TypedArray/prototype/at/polyfill.js, polyfills/document/currentScript/config.toml
Fixes https://github.com/Financial-Times/polyfill-library/issues/1129
=> fix arraybuffer polyfill to not error in ie8

polyfills/localStorage/config.toml, polyfills/localStorage/polyfill.js, polyfills/localStorage/tests.js
Resolves https://github.com/Financial-Times/polyfill-library/issues/669
=> Improves `localStorage` polyfill to store keys as `base64`

package-lock.json, package.json
This PR bumps the minimum Node.js version to 12. It also fixes support for Node.js 16 by upgrading a couple dependencies (e.g. https://github.com/formatjs/formatjs/issues/3058).
=> Bump minimum node version to 12

.github/contributing.md, karma.conf.js, package-lock.json, package.json
I was struggling to find a way to make the tests run locally, e.g. in a container or other development environment separate from your main desktop (e.g. [wikimedia/fresh](https://github.com/wikimedia/fresh/) or Vagrant-based environments, where you shell to a local container or VM).
Karma supports this very well, and I nearly got there without changing any files, but ran into the problem that Karma was each plugin to explicitly be loaded. The parameters `--browsers` and `--singleRun` can be passed to`karma start` from `npm run test-polyfills`, but this doesn't seem to work for enabling plugins, and besides, it's still suboptimal to manually install a launcher and dirtying the repo during development.
I hope this is of use. Happy to amend or otherwise accomodate any preferences to make it …
=> Enable and document locally running polyfill tests

polyfills/URL/polyfill.js, polyfills/URL/tests.js
The URL spec states that `%` and any characters following it must be considered as simple literals unless they are a pair of two hexidecimals (0-9, A-F, a-f). [1] This means that `?q=%` or `?x=%zz` are valid and simply represent their literal self, they don't decode to something else just like `?x=foo` doesn't either.
The URL spec also states that percent decoding happens at the byte level after a string has been UTF decoded, and should not be turned back into a UTF string until after the percent decoding is done. This is important because when going through percent decoding you can encounter a multi-byte character of which one byte isn't a valid UTF-8 string (or at least not the same string), and simply concatenating them does not produce the same result.
This is very different from the …
=> URL: Fix URLSearchParams decoding to not throw URIError

polyfills/URL/polyfill.js, polyfills/URL/tests.js
Ref https://github.com/Financial-Times/polyfill-library/pull/1173.
Ref https://github.com/Financial-Times/polyfill-library/issues/4.
Co-authored-by: David Chan <david@troi.org>
=> URL: Fix URLSearchParams to further avoid decoding URIError

.github/workflows/test-polyfills.yml
fixes : https://github.com/Financial-Times/polyfill-library/issues/1175
_I can not test this action as it won't run from a fork._
Steps to verify that it works as intended :
- start a test run
- cancel a job (either on GitHub or on Browserstack)
- wait for other jobs to finish
- re-run failed jobs only should be available and choosing this should trigger a partial re-run.
=> simplify test action as github now supports partial reruns

.github/workflows/test-from-fork.yml, .github/workflows/test-polyfills-weekly.yml, .github/workflows/test-polyfills.yml, .github/workflows/update-polyfill-targets.yml, test/utils/modified-polyfills-with-tests.js
GitHub workflows have build in concurrency controls.
Using these means we can remove `styfle/cancel-workflow-action` and `softprops/turnstyle`. Two 3rd party actions that required access to secrets.
Partial tests seem to have broken a while back because the checkout step no longer fetched `https://github.com/Financial-Times/polyfill-library/tree/master/`. This is required to determine the diff.
update : maybe this was done because `GITHUB_REF` was no longer valid when workflows run with a `pull_request` event. The JS has been updated so that it works for any trigger.
I've added a fetch depth of 50 which is much larger than usual pull requests will require but still smaller than fetching everything.
=> fix partial tests in CI and use native concurrency control

polyfills/TypedArray/prototype/@@iterator/config.toml, polyfills/TypedArray/prototype/@@iterator/detect.js, polyfills/TypedArray/prototype/@@iterator/polyfill.js, polyfills/TypedArray/prototype/@@iterator/tests.js, polyfills/TypedArray/prototype/entries/config.toml, polyfills/TypedArray/prototype/entries/detect.js, polyfills/TypedArray/prototype/entries/polyfill.js, polyfills/TypedArray/prototype/entries/tests.js, polyfills/TypedArray/prototype/keys/config.toml, polyfills/TypedArray/prototype/keys/detect.js, polyfills/TypedArray/prototype/keys/polyfill.js, polyfills/TypedArray/prototype/keys/tests.js, polyfills/TypedArray/prototype/toLocaleString/config.toml, polyfills/TypedArray/prototype/toLocaleString/detect.js, polyfills/TypedArray/prototype/toLocaleString/polyfill.js, polyfills/TypedArray/prototype/toLocaleString/tests.js, polyfills/TypedArray/prototype/toString/config.toml, polyfills/TypedArray/prototype/toString/detect.js, polyfills/TypedArray/prototype/toString/polyfill.js, polyfills/TypedArray/prototype/toString/tests.js, polyfills/TypedArray/prototype/values/config.toml, polyfills/TypedArray/prototype/values/detect.js, polyfills/TypedArray/prototype/values/polyfill.js, polyfills/TypedArray/prototype/values/tests.js
This PR adds the following polyfills:
* `TypedArray.prototype.@@iterator`
* `TypedArray.prototype.entries`
* `TypedArray.prototype.keys`
* `TypedArray.prototype.toLocaleString`
* `TypedArray.prototype.toString`
* `TypedArray.prototype.values`
These are all noted as missing in the `ArrayBuffer` [polyfill](https://github.com/inexorabletash/polyfill/blob/716a3f36ca10fad032083014faf1a47c638e2502/typedarray.js) (i.e. [link](https://github.com/inexorabletash/polyfill/blob/716a3f36ca10fad032083014faf1a47c638e2502/typedarray.js#L500-L501), [link](https://github.com/inexorabletash/polyfill/blob/716a3f36ca10fad032083014faf1a47c638e2502/typedarray.js#L648-L649), [link](https://github.com/inexorabletash/polyfill/blob/716a3f36ca10fad032083014faf1a47c638e2502/typedarray.js#L891-L896)).
=> Adds polyfills for `TypedArray.prototype` methods

polyfills/TypedArray/prototype/toLocaleString/config.toml
add `Intl.NumberFormat.~locale.en` as a dependency
fixes : #1212
=> TypedArray.prototype.toLocaleString : Intl interop

package-lock.json, package.json, polyfills/Intl/DateTimeFormat/tests.js
Reverts Financial-Times/polyfill-library#1186
This change seems to have a serious performance regression.
Tests with polyfill combinations always give a timeout now in Chrome, Firefox and IE.
=> Revert "Bump @formatjs/intl-datetimeformat"

test/polyfills/server.js, test/polyfills/test-iframe.handlebars, test/polyfills/test-runner.handlebars
The polyfill bundles are very large in this case.
If they all have a unique url we will have nothing but cache misses have to wait for network, parsing, interpreting,...
This change makes the url the same for all tests if the bundle includes all polyfills anyway.
=> ensure browser cache when testing polyfill combinations

polyfills/Object/hasOwn/config.toml, polyfills/Object/hasOwn/detect.js, polyfills/Object/hasOwn/polyfill.js, polyfills/Object/hasOwn/tests.js
This PR adds a polyfill for `Object.hasOwn`.
=> Adds polyfill for `Object.hasOwn`

polyfills/Object/prototype/toString/config.toml, polyfills/Object/prototype/toString/detect.js, polyfills/Object/prototype/toString/polyfill.js, polyfills/Object/prototype/toString/tests.js
This PR adds a polyfill for `Object.prototype.toString` that includes `Symbol.toStringTag` support.
=> Adds polyfill for `Object.prototype.toString`

polyfills/IntersectionObserver/polyfill.js
This PR adds `x` and `y` to all instances of `IntersectionObserverEntry` in the `IntersectionObserver` polyfill.
Resolves https://github.com/Financial-Times/polyfill-library/issues/116.
=> Adds `x` and `y` to `IntersectionObserverEntry`

polyfills/CharacterData/prototype/after/config.toml, polyfills/CharacterData/prototype/after/detect.js, polyfills/CharacterData/prototype/after/polyfill.js, polyfills/CharacterData/prototype/before/config.toml, polyfills/CharacterData/prototype/before/detect.js, polyfills/CharacterData/prototype/before/polyfill.js, polyfills/CharacterData/prototype/nextElementSibling/config.toml, polyfills/CharacterData/prototype/nextElementSibling/detect.js, polyfills/CharacterData/prototype/nextElementSibling/polyfill.js, polyfills/CharacterData/prototype/previousElementSibling/config.toml, polyfills/CharacterData/prototype/previousElementSibling/detect.js, polyfills/CharacterData/prototype/previousElementSibling/polyfill.js, polyfills/CharacterData/prototype/remove/config.toml, polyfills/CharacterData/prototype/remove/detect.js, polyfills/CharacterData/prototype/remove/polyfill.js, polyfills/CharacterData/prototype/replaceWith/config.toml, polyfills/CharacterData/prototype/replaceWith/detect.js, polyfills/CharacterData/prototype/replaceWith/polyfill.js
This PR adds polyfills for `CharacterData.prototype`:
* `after`
* `before`
* `nextElementSibling`
* `previousElementSibling`
* `remove`
* `replaceWith`
This list includes all properties of `CharacterData.prototype` that may be missing from the browsers we target, based on https://developer.mozilla.org/en-US/docs/Web/API/CharacterData#browser_compatibility.
Resolves https://github.com/Financial-Times/polyfill-library/issues/214.
=> Adds `CharacterData.prototype` polyfills

polyfills/Node/prototype/getRootNode/config.toml, polyfills/Node/prototype/getRootNode/detect.js, polyfills/Node/prototype/getRootNode/polyfill.js, polyfills/Node/prototype/getRootNode/tests.js, polyfills/Node/prototype/isConnected/config.toml, polyfills/Node/prototype/isConnected/detect.js, polyfills/Node/prototype/isConnected/polyfill.js, polyfills/Node/prototype/isConnected/tests.js
This PR adds polyfills for `Node.prototype.getRootNode` and `Node.prototype.isConnected`. It is based on https://github.com/Financial-Times/polyfill-library/pull/485 and https://github.com/Financial-Times/polyfill-library/pull/486.
Resolves https://github.com/Financial-Times/polyfill-library/issues/326.
=> Adds `Node.prototype.getRootNode` and `Node.prototype.isConnected` polyfills

polyfills/Array/prototype/findLast/config.toml, polyfills/Array/prototype/findLast/detect.js, polyfills/Array/prototype/findLast/polyfill.js, polyfills/Array/prototype/findLast/tests.js, polyfills/Array/prototype/findLastIndex/config.toml, polyfills/Array/prototype/findLastIndex/detect.js, polyfills/Array/prototype/findLastIndex/polyfill.js, polyfills/Array/prototype/findLastIndex/tests.js, polyfills/TypedArray/prototype/findLast/config.toml, polyfills/TypedArray/prototype/findLast/detect.js, polyfills/TypedArray/prototype/findLast/polyfill.js, polyfills/TypedArray/prototype/findLast/tests.js, polyfills/TypedArray/prototype/findLastIndex/config.toml, polyfills/TypedArray/prototype/findLastIndex/detect.js, polyfills/TypedArray/prototype/findLastIndex/polyfill.js, polyfills/TypedArray/prototype/findLastIndex/tests.js
This PR adds the following ES2023 polyfills:
* `Array.prototype.findLast`
* `Array.prototype.findLastIndex`
* `%TypedArray%.prototype.findLast`
* `%TypedArray%.prototype.findLastIndex`
=> Adds `findLast` and `findLastIndex` polyfills

package-lock.json, package.json
Reverts Financial-Times/polyfill-library#1233
I don't think we can bump mocha 7 major versions without making any changes :)
=> Revert "Bump minimist and mocha"

polyfills/Error/cause/tests.js, polyfills/_InstallErrorCause/polyfill.js
This PR fixes an `Error` prototype issue in `_InstallErrorCause`, which was identified in https://github.com/Financial-Times/polyfill-library/pull/1257.
See https://github.com/Financial-Times/polyfill-library/actions/runs/3869344912/jobs/6595380297 for the `polyfillCombinations` test failure.
=> Fixes `Error` prototype in `_InstallErrorCause`

.github/workflows/test-polyfills.yml
A comment `/ok-to-test` on fork-based pull requests runs tests.
In the test action we check to see if the pull request head matches the commit which was ok'ed with a comment:
https://github.com/Financial-Times/polyfill-library/blob/28f938fa6fbf537b97ee0492a68b47358c6301ba/.github/workflows/test-polyfills.yml#L69
If that is the case we checkout the PR head by PR number: https://github.com/Financial-Times/polyfill-library/blob/28f938fa6fbf537b97ee0492a68b47358c6301ba/.github/workflows/test-polyfills.yml#L80
In theory, there's a very small window between Github deciding to run an action and checking out the code where a malicious actor could push unauthorised code. To avoid this we can checkout code using `${{ github.event.client_payload.slash_command.sha }}` instead of
`refs/pull/${{ …
=> backstage: only checkout approved commits when running tests

.github/workflows/test-polyfills.yml
Reverts Financial-Times/polyfill-library#1264
Closes https://github.com/Financial-Times/polyfill-library/issues/1273
=> Revert "backstage: only checkout approved commits when running tests"

polyfills/Map/polyfill.js, polyfills/Map/tests.js
Before this change map keys for non string types would be the same as string values that happened to be the same as `x.toString()`.
- `99` and `'99'`
- `true` and `'true'`
- `null` and `'null'`
- ...
We now prepend the type name and a unique marker (a newly generated UUID).
This makes the chance of collisions really small.
=> map polyfill : ensure that map keys are sufficiently unique

polyfills/IntersectionObserver/polyfill.js, polyfills/IntersectionObserver/tests.js, polyfills/IntersectionObserverEntry/config.toml
see : https://github.com/Financial-Times/polyfill-library/issues/1282
=> serve `isIntersecting` polyfill to chromium based browsers

polyfills/TypedArray/prototype/entries/polyfill.js, polyfills/TypedArray/prototype/findLast/polyfill.js, polyfills/TypedArray/prototype/findLastIndex/polyfill.js, polyfills/TypedArray/prototype/keys/polyfill.js
- Use `fnName` variable instead of repeated identical strings, for better minification
- Remove unnecessary `createMethodProperties(fn)` function, in favour of same structure in all different polyfills
=> Streamline TypedArray polyfills

polyfills/Array/prototype/sort/config.toml, polyfills/Array/prototype/sort/polyfill.js, polyfills/Array/prototype/sort/tests.js
This PR fixes `Array.prototype.sort` so it properly handles sparse arrays, arrays containing `undefined`, and `comparefn` that returns invalid results. This implementation is based on https://github.com/zloirock/core-js/blob/master/packages/core-js/internals/array-sort.js.
=> Fixes `Array.prototype.sort` for sparse arrays

polyfills/Array/prototype/sort/config.toml, polyfills/Array/prototype/sort/polyfill.js, polyfills/Array/prototype/sort/tests.js
This PR removes the unnecessary `Number.isNaN` dependency in `Array.prototype.sort`. It also adds more tests to `Array.prototype.sort`.
This is a follow-up to https://github.com/Financial-Times/polyfill-library/pull/1289.
=> Removes `Array.prototype.sort` dependency on `Number.isNaN`

polyfills/Array/prototype/sort/tests.js
Extra tests for `Array.prototype.sort` to ensure that it is really doing a stable sort.
_Initially created to debug a test failure in `Array.prototype.toSorted`_
-----
Original message :
The stable sort polyfill is causing issues for `toSorted`.
Somehow it gives unexpected results with sparse arrays.
I haven't found the issue yet, but these are some extra tests.
@mhassan1 I've been testing on Edge 15 (but 18 should fail aswel) with this url :
http://bs-local.com:9876/test?includePolyfills=yes&always=no&feature=Array.prototype.toSorted&polyfillCombinations=yes
Maybe you spot something I am overlooking :)
=> `Array.prototype.sort` : extra tests

polyfills/console/exception/polyfill.js
Provides working polyfill for ``console.exception`` instead of noop function
The thing is according to **[MDN Web APIs reference]( https://developer.mozilla.org/en-US/docs/Web/API/console)** ``console.exception`` is an obsolete alias for ``console.error`` method
So, if ``error`` exists in ``console``, we can provide it under ``console.exception`` name and thus get this polyfill working. If there's no ``error`` in ``console``, we're falling back to noop ``function exception() {}``
=> Working polyfill for console.exception instead of noop function

test/polyfills/browsers.toml, test/polyfills/browserstackBrowsers.toml
This PR drops all Android 5.0 devices from the BrowserStack browser list, since they have been removed by BrowserStack.
=> Drop Android 5.0 from test suite
