JakeChampion/polyfill-library

- polyfills/Element/prototype/dataset/polyfill.js
> Make Element.prototype.dataset properties enumerable

- .circleci/config.yml
- polyfills/Set/polyfill.js
- polyfills/Set/tests.js
- tasks/node/build-circleci-config.js
Here is the tests running without the fixed polyfill:
> Make Set comply with specification by throwing TypeError if the given argument is not iterable

- polyfills/requestAnimationFrame/config.json
- polyfills/requestAnimationFrame/polyfill.js
Remove performance.now from raf polyfill. #34
> Remove performance.now from dep of requestanimationframe

- lib/index.js
- package-lock.json
- package.json
Resolves https://github.com/Financial-Times/polyfill-library/issues/139
> use a fast LRU cache for ua parsing

- package-lock.json
- tasks/node/buildsources.js
Fixes #24 by creating a separate minifier function to deal with detect.js snippets
> Update detect minify

- polyfills/Intl/update.task.js
- polyfills/fetch/update.task.js
- tasks/node/build-circleci-config.js
> Replace fs with graceful-fs to stop too many files open error

- polyfills/Symbol/match/config.json
- polyfills/Symbol/replace/config.json
> Match/replace Symbol

- polyfills/Object/assign/polyfill.js
- polyfills/Object/assign/tests.js
Fixes https://github.com/Financial-Times/polyfill-library/issues/154
> Make Object.assign work with window.location

- polyfills/Promise/config.json
Resolves https://github.com/Financial-Times/polyfill-library/issues/108
> Serve Promise to op_mob

- polyfills/requestAnimationFrame/config.json
fixes https://github.com/Financial-Times/polyfill-library/issues/172
> Update support of requestAnimationFrame for Opera Mini

- tasks/node/buildsources.js
> preserve function names in minified code

- polyfills/Map/detect.js
> Fix broken this reference anonymous function when in strict mode

- .eslintignore
- .gitignore
- package-lock.json
- package.json
- polyfills/ResizeObserver/config.json
- polyfills/ResizeObserver/detect.js
Adding the ResizeObserver polyfill - Feature Request https://github.com/Financial-Times/polyfill-library/issues/211
> Adding the ResizeObserver polyfill

- .circleci/config.yml
- package-lock.json
- polyfills/Symbol/prototype/description/config.json
- polyfills/Symbol/prototype/description/detect.js
- polyfills/Symbol/prototype/description/polyfill.js
- polyfills/Symbol/prototype/description/tests.js
Symbol.prototype.description polyfill created
> Symbol description

- package-lock.json
- package.json
Resolves https://github.com/Financial-Times/polyfill-useragent-normaliser/issues/13
> Update useragent normaliser to version which detects WebPageTest as Chrome

- polyfills/Symbol/polyfill.js
- polyfills/Symbol/tests.js
> ({}).toString.call(null) should not be [object Window]

- polyfills/Array/prototype/fill/config.toml
fixes https://github.com/Financial-Times/polyfill-library/issues/344
> Serve Array.prototype.fill to all ie mobile

- package.json
|`npm publish` | packed size | unpacked size | files |
|---------------|--------------|----------------|------|
|`master` | 2.2 MB | 62.9 MB | 6259|
|this change | 1.4 MB | 41.4 MB  | 3083|
> Smaller npm package

- polyfills/matchMedia/config.toml
fixes https://github.com/Financial-Times/polyfill-library/issues/71
> target ie 9 with match media polyfill

- .gitignore
- polyfills/Intl/detect.js
- polyfills/Intl/update.task.js
Fixes https://github.com/Financial-Times/polyfill-library/issues/337
> Create the Intl detect based upon all the Intl locales that we have available

- polyfills/Symbol/polyfill.js
for those of us without windows
> Use `self` rather than `window` in symbol polyfill

- .github/contributing.md
This ended up fairly lengthy although I tried to keep it to only the necessary information.
Perhaps this would work better in a different document rather than the main contributing document.
As always, I welcome any feedback and if you decide you don't want to take this proposal at all that is okay.
[See the changes rendered](https://github.com/Financial-Times/polyfill-library/blob/f6de8a622d3cd457c6dbed75796792ce0171078e/.github/contributing.md#adding-a-new-polyfill) 
Closes https://github.com/Financial-Times/polyfill-library/issues/498
> Add documentation explaining how to add a polyfill

- polyfills/Element/prototype/matches/config.toml
Fixes https://github.com/Financial-Times/polyfill-library/issues/517
> Target Edge 12, 13 and 14 for Element.prototype.matches

- polyfills/navigator/sendBeacon/polyfill.js
Fixes https://github.com/Financial-Times/polyfill-library/issues/523
> If navigator.sendBeacon can not queue the work for transferring, return false as per the specification.

- polyfills/Map/polyfill.js
- polyfills/Map/tests.js
Corresponding issue --> https://github.com/Financial-Times/polyfill-library/issues/536
> Add test for empty string as key in a Map

- polyfills/HTMLCanvasElement/prototype/toBlob/polyfill.js
- polyfills/HTMLCanvasElement/prototype/toBlob/tests.js
fixes https://github.com/Financial-Times/polyfill-library/issues/208
> Ensure callback for HTMLCanvasElement.prototype.toBlob is not invoked syncronously

- polyfills/URL/polyfill.js
- polyfills/URL/tests.js
fixes https://github.com/Financial-Times/polyfill-library/issues/340
> Add URLSearchParams sort method

- test/node/lib/test-index.js
Closes https://github.com/Financial-Times/polyfill-library/issues/125
> Add test for https://github.com/Financial-Times/polyfill-library/issues/125

- polyfills/matchMedia/polyfill.js
Fixes https://github.com/Financial-Times/polyfill-library/issues/623
> Add missing listeners array on mql instances

- polyfills/matchMedia/tests.js
see: #623
This fails consistently in Safari in our tests.
> matchMedia : new test for 'addListener'

- polyfills/Intl/PluralRules/update.task.js
The other Intl polyfills use `'Intl' in self`
> Intl polyfill detect consistency.

- polyfills/Symbol/polyfill.js
- polyfills/Symbol/prototype/description/polyfill.js
- polyfills/Symbol/prototype/description/tests.js
- polyfills/_ESAbstract/Type/polyfill.js
Resolves https://github.com/Financial-Times/polyfill-library/issues/899
> rewrite Symbol.prototype.description polyfill so it passes tests

- polyfills/DOMTokenList/prototype/forEach/config.toml
- polyfills/DOMTokenList/prototype/forEach/detect.js
- polyfills/DOMTokenList/prototype/forEach/polyfill.js
- polyfills/DOMTokenList/prototype/forEach/tests.js
- polyfills/_DOMTokenList/config.toml
- polyfills/_DOMTokenList/polyfill.js
fixes : #534
Had to add `that.forEach = Array.prototype.forEach;` to `_DOMTokenList`.
Unsure if this is the correct way.
> Add DOMTokenList.prototype.forEach polyfill

- polyfills/_ESAbstract/StringIndexOf/polyfill.js
Unsure why the code was as it was before.
I had an "undefined" error in console that went away with this change
> fix StringIndexOf

- .github/workflows/lint.yml
- .github/workflows/publish-to-npm-as-latest.yml
- .github/workflows/publish-to-npm-as-prerelease.yml
- .github/workflows/test-polyfills-weekly.yml
- .github/workflows/test-polyfills.yml
- .github/workflows/unit-test.yml
- .github/workflows/update-polyfill-targets.yml
use `npm` cache
docs and details : https://github.com/actions/setup-node/releases/tag/v2.2.0
> github workflows : add npm cache

- package-lock.json
- package.json
this fixes issues with normalising ios 14 browsers
Resolves #1079
> update to latest version of @financial-times/polyfill-useragent-normaliser

- polyfills/Intl/PluralRules/config.toml
Resolves https://github.com/Financial-Times/polyfill-library/issues/650
> Update guidance for Intl.PluralRules to mention locales have no subtags

- polyfills/Intl/DateTimeFormat/~timeZone/all/config.toml
- polyfills/Intl/DateTimeFormat/~timeZone/golden/config.toml
_And I immediately forgot to sync these._
> fix time zone browsers list

- polyfills/Intl/DateTimeFormat/config.toml
- polyfills/Intl/DateTimeFormat/~timeZone/all/config.toml
- polyfills/Intl/DateTimeFormat/~timeZone/golden/config.toml
- polyfills/Intl/DisplayNames/config.toml
- polyfills/Intl/ListFormat/config.toml
- polyfills/Intl/Locale/config.toml
- polyfills/Intl/NumberFormat/config.toml
- polyfills/Intl/PluralRules/config.toml
- polyfills/Intl/RelativeTimeFormat/config.toml
- polyfills/Intl/getCanonicalLocales/config.toml
> update Intl.* config's

- .github/workflows/test-polyfills.yml
Reverts Financial-Times/polyfill-library#1122
> Revert "allow workflow_dispatch in test-polyfills.yml"

- polyfills/AggregateError/config.toml
- polyfills/AggregateError/detect.js
- polyfills/AggregateError/polyfill.js
- polyfills/AggregateError/tests.js
- polyfills/Promise/allSettled/config.toml
- polyfills/Promise/allSettled/detect.js
- polyfills/Promise/allSettled/polyfill.js
- polyfills/Promise/allSettled/tests.js
- polyfills/Promise/any/config.toml
- polyfills/Promise/any/detect.js
- polyfills/Promise/any/polyfill.js
- polyfills/Promise/any/tests.js
- polyfills/_ESAbstract/IterableToList/config.toml
- polyfills/_ESAbstract/IterableToList/polyfill.js
Resolves https://github.com/Financial-Times/polyfill-library/issues/862
> Adds `Promise.any`, `Promise.allSettled`, and `AggregateError` polyfills

- polyfills/ArrayBuffer/isView/config.toml
- polyfills/ArrayBuffer/isView/detect.js
- polyfills/ArrayBuffer/isView/polyfill.js
- polyfills/ArrayBuffer/isView/tests.js
- polyfills/TypedArray/prototype/at/tests.js
Resolves https://github.com/Financial-Times/polyfill-library/issues/167
> Adds `ArrayBuffer.isView` polyfill

- polyfills/Node/prototype/isSameNode/config.toml
- polyfills/Node/prototype/isSameNode/detect.js
- polyfills/Node/prototype/isSameNode/polyfill.js
- polyfills/Node/prototype/isSameNode/tests.js
Resolves https://github.com/Financial-Times/polyfill-library/issues/300
> Adds `Node.prototype.isSameNode` polyfill

- polyfills/HTMLCollection/prototype/@@iterator/config.toml
- polyfills/HTMLCollection/prototype/@@iterator/detect.js
- polyfills/HTMLCollection/prototype/@@iterator/polyfill.js
- polyfills/HTMLCollection/prototype/@@iterator/tests.js
Hello,
Old Edge lacks of `HTMLCollection.prototype.@@iterator`, so here goes the polyfill for it.
Proof
> Polyfill for HTMLCollection.prototype.@@iterator

- .github/workflows/test-polyfills-weekly.yml
Remnant of https://github.com/Financial-Times/polyfill-library/pull/1199
> fix weekly test suite

- polyfills/AggregateError/config.toml
- polyfills/AggregateError/polyfill.js
- polyfills/AggregateError/tests.js
- polyfills/Error/cause/config.toml
- polyfills/Error/cause/detect.js
- polyfills/Error/cause/polyfill.js
- polyfills/Error/cause/tests.js
- polyfills/_ESAbstract/CreateNonEnumerableDataPropertyOrThrow/config.toml
- polyfills/_ESAbstract/CreateNonEnumerableDataPropertyOrThrow/polyfill.js
- polyfills/_ESAbstract/DefinePropertyOrThrow/config.toml
- polyfills/_ESAbstract/DefinePropertyOrThrow/polyfill.js
- polyfills/_InstallErrorCause/config.toml
- polyfills/_InstallErrorCause/polyfill.js
This PR adds a polyfill for `Error.cause`.
> Adds `Error.cause` polyfill

- polyfills/structuredClone/config.toml
- polyfills/structuredClone/detect.js
- polyfills/structuredClone/polyfill.js
- polyfills/structuredClone/tests.js
This adds a basic implementation of structuredClone. Of course not all features can be polyfilled, but this one works quite well.
> Adds structuredClone. Fixes #1147

- polyfills/Map/groupBy/config.toml
- polyfills/Map/groupBy/detect.js
- polyfills/Map/groupBy/polyfill.js
- polyfills/Map/groupBy/tests.js
- polyfills/Object/groupBy/config.toml
- polyfills/Object/groupBy/detect.js
- polyfills/Object/groupBy/polyfill.js
- polyfills/Object/groupBy/tests.js
- polyfills/_ESAbstract/AddValueToKeyedGroup/config.toml
- polyfills/_ESAbstract/AddValueToKeyedGroup/polyfill.js
- polyfills/_ESAbstract/GroupBy/config.toml
- polyfills/_ESAbstract/GroupBy/polyfill.js
This PR adds polyfills for `Object.groupBy` and `Map.groupBy`.
> Adds `Object.groupBy` and `Map.groupBy`
